#server:
#  servlet:
#    context-path: /thirdpartyApi
spring:
  profiles:
    active: dev
###################  mybatis配置  ###################
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.heartmelody.dudui.domain.dto
  configuration:
    map-underscore-to-camel-case: true

